name: Issue days labeler

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * *'

jobs:
  days-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: label issue days
        uses: chipodeil/IssueInProgressDaysLabeler@master
        with:
          github-token: "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"
          days-mode: "EveryDay"
          label-to-increment: "This issues assigned {0} days"
          since-days: "30"
          auto-cleanup: "true"